### ISSUE TITLE
Consider support for schema used by the PowerDNS ldap backend

### ISSUE THREAD

**Issue by bbusse** [xoe-labs/coredns-ldap#2]
See https://doc.powerdns.com/authoritative/backends/ldap.html It also supports IPv6 and would ease the migration from PowerDNS

**Comment by blaggacao** [comment]
I would tend to favor a schema-less implementation, while being able to account for different schema in the config. My idea was to use ldap queries to acomplish that.

**Comment by bbusse** [comment]
I see, alright. I will try to make it work this way then

**Comment by bbusse** [comment]
I can confirm that it works as intended. Got it to work this way with the schema and minor modifications to support AAAA records
